### ISSUE TITLE
Include uncertainty in measured quantities?

### ISSUE THREAD

**Issue by Sleort** [rahulkp220/PeriodicTable.jl#11]
Measured quantities, like melting points an boiling points, always come (and should be presented) with an uncertainty. What about including these, e.g. by using [Measurements.jl](https://github.com/JuliaPhysics/Measurements.jl)?

**Comment by rahulkp220** [comment]
@Sleort That's an interesting suggestion.Would you mind adding this functionality through a PR?

**Comment by Sleort** [comment]
I had a quick look at it, and although introducing the functionality itself shouldn't be too hard, updating all the (automatically generated) data would be a major project I unfortunately don't have time for... (Besides, if one starts being more serious, it's no longer sufficient to say just "melting/boiling point", as such quantities also depends on the specific allotrope/isotope etc.)

I fixed a few grave errors, though (due to the automatic table generation, I presume)

**Comment by giordano** [comment]
Where is the data? Perhaps I can have a look at this.

**Comment by rahulkp220** [comment]
@giordano sure. It's [here](https://github.com/rahulkp220/PeriodicTable.jl/blob/master/src/elements.jl)

**Comment by giordano** [comment]
@rahulkp220 Yeah, I saw the source code of this package, I was asking for the data of the uncertainty of the melting points.  I can't find them anywhere.

Perhaps @Sleort knows a source where this information can be retrieved.

**Comment by rahulkp220** [comment]
@giordano Oh okay.

**Comment by Sleort** [comment]
@giordano I tried to track down some uncertainty data, but it seems to be somewhat tricky (as also mentioned in the [discussion](https://en.wikipedia.org/wiki/Talk%3AMelting_points_of_the_elements_(data_page)) of [this](https://en.wikipedia.org/wiki/Melting_points_of_the_elements_(data_page)) more comprehensive list of melting points at Wikipedia.) I guess one would have to look into the original research papers to find such information...

Also, as I mentioned above (after having given my proposal a second thought), melting/boiling points (especially accurate ones) really depend on details (allotrope, isotrope, pressure...) beyond merely "element", so giving an accurate "value with uncertainty for element X" could be somewhat misleading...

**Comment by carstenbauer** [comment]
@Sleort I think you're right that uncertainties aren't that simple and thus would be misleading. Should we close this?

**Comment by Sleort** [comment]
Yeah... For now, at least.
