### ISSUE TITLE
Why is Element mutable?

### ISSUE THREAD

**Issue by jw3126** [rahulkp220/PeriodicTable.jl#21]
I just realized, that `Element` is a mutable struct. This seems strange, is it intended?

**Comment by rahulkp220** [comment]
No, it's not intended, neither the `Element` should be mutable. Should be changed to just `struct`. @crstnbr @stevengj agreed?

**Comment by carstenbauer** [comment]
Good catch, certainly not intended. Dropping the `mutable` should work without any further changes. @jw3126 wanna make a simple PR?

**Comment by jw3126** [comment]
sure!
