### ISSUE TITLE
Consider moving PeriodicTable.jl to JuliaPhysics

### ISSUE THREAD

**Issue by carstenbauer** [rahulkp220/PeriodicTable.jl#24]
Would make sense IMHO. What do you think @rahulkp220, @giordano?

**Comment by giordano** [comment]
I consider the periodic table something more Chemistry-ish, but sure it's also used in Physics.  The border between Chemistry and Physics is not a cutline, anyway.  Also, I'm not aware of a JuliaChemistry organisation on GitHub.

In any case, if @rahulkp220 is happy to move the repo to the organisation, why not!

**Comment by rahulkp220** [comment]
@giordano @crstnbr sure, let's do it. Also I would love to join the JuliaPhysics org as well.

**Comment by giordano** [comment]
@rahulkp220 I should have sent you an invitation to the organisation.  After you join it, you should be able to transfer ownership in the repo's settings
