### ISSUE TITLE
Lookup element by its symbol?

### ISSUE THREAD

**Issue by caseykneale** [rahulkp220/PeriodicTable.jl#25]
It'd be really nice to have built in constructors/convenience functions that query available atoms for a given property.

IE:
```
PeriodicTable.Elements("H") == PeriodicTable.Elements(Hydrogen)

or

lookitup(symbol) = [ e for e in PeriodicTable.elements if e.symbol == symbol][1]
e = lookitup("H")
```

I'm kicking around a package that might benefit from this...

**Comment by rjpower4** [comment]
This is implemented as 

``` julia 
elements[:ElementSymbol]
```

**Comment by caseykneale** [comment]
forgot about this! Thanks!
