### ISSUE TITLE
pretty-printing

### ISSUE THREAD

**Issue by stevengj** [rahulkp220/PeriodicTable.jl#3]
You probably want to [overload `Base.show`](https://docs.julialang.org/en/stable/manual/types/#Custom-pretty-printing-1) for `Element` in order to display it in a nicer way.

**Comment by rahulkp220** [comment]
Fixed by https://github.com/rahulkp220/PeriodicTable.jl/pull/4 
Credits: @lancebeet

**Comment by stevengj** [comment]
That only added pretty-printing of the table, not of an individual `Element`.
