### ISSUE TITLE
Atomic weights slightly wrong

### ISSUE THREAD

**Issue by NicholasWMRitchie** [rahulkp220/PeriodicTable.jl#56]
I believe the source of the atomic weight data is the [IUPAC 2021 tabulation](https://iupac.qmul.ac.uk/AtWt/).  However, there is a subtle misinterpretation of the data in this table that plays through to the values of the atomic weights in PeriodicTable.jl.

The reported uncertainty in the atomic weight column is being interpreted incorrectly.

In PeriodicTable.jl, the atomic weight of Ne is reported as `20.17976u`.  In the IUPAC table, it is listed as `20.1797(6)`.  `20.1797(6)` does not mean `20.17976`.  It means $20.1797 \pm 0.0006$.
Similarly, Yb has an atomic weight of  `173.045(10)` or $173.045 \pm 0.010$. 

The correct interpretation of the parenthesis at the end is to assume this amount of uncertainty in the final digits of the preceding number.

This error is repeated for all elements with reported uncertainties on the atomic weights.

**Comment by NicholasWMRitchie** [comment]
I see that this has been previously reported.

**Comment by carstenbauer** [comment]
Thanks for the issue. Would be great if you could prepare a PR that fixes this for all elements.

**Comment by NicholasWMRitchie** [comment]
@carstenbauer  Done. 😃
